# providers
MINIO_PROVIDER = "minio"
AWS_PROVIDER = "aws"
SUPPORTED_S3_PROVIDERS = [MINIO_PROVIDER, AWS_PROVIDER]

# exposers
EMPTY_EXPOSER = "empty"
HTML_EXPOSER = "html"
JSON_EXPOSER = "json"
SUPPORTED_EXPOSER_TYPES = [EMPTY_EXPOSER, HTML_EXPOSER, JSON_EXPOSER]

# miscellaneous
ALL_BUCKETS_ALLOWED = "all_buckets"
ALL_VALUES_ALLOWED = []
NO_EXPOSER_LOGGING = "OFF"
LOG_LEVELS = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", NO_EXPOSER_LOGGING]

# app
APP_NAME = "s3-bucket-exposer"
APP_VERSION = "beta"
APP_FULL_NAME = f"{APP_NAME} {APP_VERSION}"
