# Variables
S3_PROVIDER = "S3_PROVIDER"
MINIO_ENDPOINT = "MINIO_ENDPOINT"
S3_ACCESS_KEY = "S3_ACCESS_KEY"
S3_SECRET_KEY = "S3_SECRET_KEY"
EXPOSER_ALLOWED_BUCKETS = "EXPOSER_ALLOWED_BUCKETS"
EXPOSER_TYPE = "EXPOSER_TYPE"
EXPOSER_LOG_LEVEL = "EXPOSER_LOG_LEVEL"

# Default values
S3_ACCESS_KEY_DEFAULT = "admin"
S3_SECRET_KEY_DEFAULT = "password"
EXPOSER_LOG_LEVEL_DEFAULT = "DEBUG"

# Docker
DOCKER_IMAGE_NAME = "s3-bucket-exposer"
DOCKER_IMAGE_TAG = "candidate"
DOCKER_CONTAINER_NAME = "s3-bucket-exposer"
MINIO_CONTAINER_NAME = "minio-local-s3"
