name: Unittests
on: [push, pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip3 install -r tests-requirements.txt -r s3-bucket-exposer/requirements.txt
      - name: Run unit tests
        run: cd s3-bucket-exposer && python3 -m unittest
